mongodb:
    image: tutum/mongodb:3.2
    environment:
        AUTH: "no"
    restart: always
mariadb:
    image: mariadb:10.1
    env_file: .env
    environment:
        # Fix https://goo.gl/fUTycl
        MYSQL_HOST:
    ports:
        - "3306:3306"
    volumes:
        - ./tools/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    restart: always
concava:
    build: .
    env_file: .env
    ports:
        - "3000:3000"
        - "1883:1883"
    volumes:
        - ./config/concava.js:/data/config.js:ro
    links:
        - mariadb
        - mongodb
    restart: always
